name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: Rockyjr-git
        password: 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
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
