name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    #- name: Log into registry
      #uses: docker/login-action@v1
      #with:
        #registry: ghcr.io
        #username: ${{ github.actor }}
        #password: ${{ secrets.GITHUB_TOKEN }}
        
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: repo/image
        tags: v3
        registry: ghcr.io
        dockerfile: Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
